### ISSUE TITLE
추후 리팩토링이 필요한 부분

### ISSUE THREAD

**Issue by waterfogSW** [prgrms-be-devcourse/BE-02-Slack#37]
1. encodedWorkspaceId, decodedWorkspaceId, key 등 워크스페이스 id 명명 규칙 통일 필요

2. 레이어별 DTO 전략

3. 몇몇 자동포멧팅이 적용되어있지 않은 부분들이 있습니다. 

4. Response에 대한 컨벤션? 을 맞춰 보면 좋을것 같습니다. (ex. HttpStatus)
<img width="654" alt="image" src="https://user-images.githubusercontent.com/57293011/176358357-b6acbc85-34e8-4dd1-a444-4e6e9ea7211c.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/57293011/176358417-6226c8ba-8445-4179-81b4-4469823a6258.png">

5. 몇몇 생성자에 검증 로직이 존재하지 않습니다. 추가가 필요할것 같습니다

6. isNotBlank를 import 하는 라이브러리가 각자 다른경우가 있는것 같습니다. (log4j, spring util, 등등)

7. 에러메시지 https://github.com/prgrms-be-devcourse/BE-02-Slack/pull/48#discussion_r910718841

8. common폴더 내용물 분류 -> 인증관련설정 모아둔 패키지, 웹소켓 관련설정 모아둔 패키지 만들기

9. 하영님이 comment다신 부분과 비슷한 내용 기본 URI에 workspaceId가 Pathvariable로 포함되어 있는데 사용되지 않는 경우?

**Comment by gkdud583** [comment]
9. URI 설계 리팩토링
현재 채널 URI는 "api/v1/workspaces/{workspaceid}/channels/{channelid} 이런식으로 되어 있는데요.
이렇게 공통으로 맞추고 개발을 하다보니까 실제 서비스 로직에서는 pathvariable로 넘어오는 workspaceid를 사용하지 않는 경우가 있습니다.
그래서 이런 경우엔 URI 설계에서 워크스페이스를 제외하고 /api/v1/channels 이런식으로 가야할지, 아니면 사용하지 않더라도 기존의 방식(api/v1/workspaces/{workspaceid}/channels/{channelid}) 을 유지할지 논의가 필요합니다!
이거 관련해서 레이에게 dm을 보냈었는데 레이의 의견은 "/api/v1/channels로 가는게 맞다" 고 하셨습니다! 현재는 기능 개발에 집중하고 나중에 리팩토링 할 때 이야기하면 좋을 것 같습니다~
<img width="497" alt="스크린샷 2022-07-04 오후 3 22 02" src="https://user-images.githubusercontent.com/60775067/177093708-c1045383-05b1-49ab-8177-7a9988b46bac.png">
<img width="495" alt="스크린샷 2022-07-04 오후 3 22 19" src="https://user-images.githubusercontent.com/60775067/177093721-46005473-e147-47fd-bf0b-8f8c0d6cda65.png">

**Comment by waterfogSW** [comment]
https://github.com/prgrms-be-devcourse/BE-02-Slack/pull/51#discussion_r912346907
