### ISSUE TITLE
다이렉트 메시지, 채널 메시지 구분 관련

### ISSUE THREAD

**Issue by waterfogSW** [prgrms-be-devcourse/BE-02-Slack#55]
## 요약 

메시지, 다이렉트 메시지 엔티티를 나누지 말고 하나로 사용하자

## 기존 설계

![image](https://user-images.githubusercontent.com/28651727/177026733-ba5db57a-7954-496e-8909-3819fef8f4b9.png)

기존 설계에서는 채널 메시지와 다이렉트 메시지가 나뉘어있었는데요, 
채널 엔티티가 다이렉트 채널 엔티티, 일반 채널엔티티 두 종류로 나뉨에 따라 그와 연관관계를 갖는 메시지 엔티티, 다이렉트 메시지 엔티티로 나뉘어야 하기 때문입니다.

하지만 이렇게 나눌경우 채널에서 메시지를 조회하는것과, 다이렉트 채널에서 메시지를 조회하는것이 동일한 작업임에도 불구하고 엔티티가 다르기때문에 다른 api가 나와야하는 문제가 생깁니다. 이렇게 대부분의 로직이 비슷하거나 거의 같기 때문에 **다이렉트 메시지와 메시지를 나누는것은 코드의 중복을 불가피하게 하는것**으로 생각되었습니다. 

그래서 생각했던 아이디어 하나가 메시지와 채널을 직접 연관관계를 맺지 않고, 인코딩된 채널 id 값을 메시지의 컬럼으로 두자는 것입니다. 이렇게 하면 사용자가 채널의 메시지를 조회할때 현재 채널의 인코딩된 id 값으로 MessageRepository 를 조회하기만 하면 됩니다. 

하지만 다이렉트 채널의 id값이 1이고, 채널의 id값이 1이면 둘의 인코딩된 채널 id값은 같습니다. 이경우에 다이렉트 채널과 채널의 메시지가 동시에 조회되는 현상이 발생할 수 있습니다. 

이러한 문제는 슬랙과 동일하게 채널의 인코딩된 id 맨앞에는 C, 다이렉트 채널의 인코딩된 id 맨앞에는 D를 붙여 둘을 구분하면 될것같습니다. 기존에 구현했던 ID인코더를 일부 수정하기만 하면 됩니다.

## 슬랙 

![image](https://user-images.githubusercontent.com/28651727/177026672-7ba15893-35ad-4e8f-8dd0-37036cdfeca1.png)

슬랙의 경우 위의 그림과 같이 워크스페이스 ID는 T로 시작하고, 채널 ID는 C, 다이렉트 채널 ID는 D로 시작합니다

저희도 이렇게 다이렉트채널과 일반 채널을 인코딩된 ID값으로 구분한다면, 굳이 채널의 메시지와 다이렉트채널 메시지를 구분하지 않아도 될것 같습니다.

**Comment by UJ15** [comment]
아 너무 좋습니다 오늘 메세지 아주 시체로 만들어 버리죠

**Comment by gkdud583** [comment]
👍👍👍
